### ISSUE TITLE
Consuming web Components like polymer's <paper-button> in Angular 2.0 Alpha

### ISSUE THREAD

**Issue by tkhemani** [dgs700/angular-custom-element#13]
@dgs700, Is it possible to consume web Components like polymer's 'paper-button' in Angular 2.0 Alpha today? 

Can you share some guidelines/sample for this. I've been trying to do this ever since the Angular 2 alpha was released

**Comment by dgs700** [comment]
You want to ask the NG 2.0 team this question since only they really know what functionality is in this early, early, early alpha release.
